name: CI Build python alpine 3.7

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [python]
        image-version: [3.7-alpine-django]

    steps:
    - uses: actions/checkout@v1
    - name: docker build and push aliyun
      env:
        aliyun_username: ${{ secrets.DOCKER_USERNAME }}
        aliyun_password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        sudo docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-beijing.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
        sudo docker build . --file Dockerfile -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} registry.cn-beijing.aliyuncs.com/kts/python:${{ matrix.image-version }}
        sudo docker push registry.cn-beijing.aliyuncs.com/kts/python:${{ matrix.image-version }}

